### ISSUE TITLE
javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by mpkmtv** [Hakky54/mutual-tls#1]
Thank you. Everything worked fine until "Two way TLS based on trusting the Certificate Authority" That did not work and resulted in the error shown below.  I tried various JDKs and other suggestions from the internet. Nothing worked.

 @Demo
  Scenario: Saying hello to the Server       # src/test/resources/features/Hello.feature:4
    Given Server is alive                    # HelloStepDefs.serverIsAlive()
    When I say hello                         # HelloStepDefs.iSayHello()
      javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)

**Comment by Hakky54** [comment]
Hi mpkmtv,

The stack trace is complaining that one or both of the trustAnchor parameters are empty. Could you post your application.yml file of the client here?

**Comment by mpkmtv** [comment]
MY BAD!!!

THANK YOU !

David
________________________________

**Comment by mpkmtv** [comment]
I fixed the application.yml file for the client  , but it still gives me the exception. I'm on Mac OSX . Not sure what i did wrong.

client application.yml :
spring:
  main:
    banner-mode: "off"

client:
  ssl:
    enabled: true
    key-store: identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: truststore.jks
    trust-store-password: secret


server  application.yml :
spring:
  banner:
    location: classpath:banner.txt

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:identity.jks
    key-password: secret
    key-store-password: secret
    trust-store: classpath:truststore.jks
    trust-store-password: secret
    client-auth: need
  tomcat:
    accesslog:
      enabled:  true
    basedir:  /tmp/tomcat


________________________________

**Comment by Hakky54** [comment]
I copied your properties to the corresponding application.yml file of the server and client ond my machine and I am not getting an exception. Could you provide your stack-trace?

**Comment by mpkmtv** [comment]
Thank you so much for your help. I did it a few times from scratch following the GitHub instructions. The result is the same.
here is the exception:


....

org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@7ee8290b, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@1f59a598, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@1e178745, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@192c3f1e]

14:12:05.945 [main] DEBUG org.springframework.test.context.support.TestPropertySourceUtils - Adding inlined properties to environment: {spring.jmx.enabled=false, server.port=-1}


  .   ____          _            __ _ _

 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \

( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \

 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )

  '  |____| .__|_| |_|_| |_\__, | / / / /

 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::        (v2.1.2.RELEASE)


2019-04-29 14:12:06.417  INFO 84979 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Starting HelloStepDefs on davids-MacBook-Pro-2.local with PID 84979 (started by wdavid in /Users/wdavid/GitHub/mtls/client)

2019-04-29 14:12:06.419  INFO 84979 --- [           main] n.a.client.stepdefs.HelloStepDefs        : No active profile set, falling back to default profiles: default

2019-04-29 14:12:07.227  INFO 84979 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Started HelloStepDefs in 1.279 seconds (JVM running for 2.485)

Feature: Securing the connection between you and the world


  @Demo

  Scenario: Saying hello to the Server       # src/test/resources/features/Hello.feature:4

    Given Server is alive                    # HelloStepDefs.serverIsAlive()

    When I say hello                         # HelloStepDefs.iSayHello()

      javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)

at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)

at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)

at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)

at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)

at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)

at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

at nl.altindag.client.stepdefs.HelloStepDefs.iSayHello(HelloStepDefs.java:28)

at ✽.I say hello(src/test/resources/features/Hello.feature:6)

Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)

at sun.security.validator.Validator.getInstance(Validator.java:181)

at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)

at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)

at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)

at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)

at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)

at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)

at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)

at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)

at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)

at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

at nl.altindag.client.stepdefs.HelloStepDefs.iSayHello(HelloStepDefs.java:28)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at cucumber.runtime.Utils$1.call(Utils.java:26)

at cucumber.runtime.Timeout.timeout(Timeout.java:16)

at cucumber.runtime.Utils.invoke(Utils.java:20)

at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:48)

at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)

at cucumber.runner.TestStep.executeStep(TestStep.java:63)

at cucumber.runner.TestStep.run(TestStep.java:49)

at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)

at cucumber.runner.TestCase.run(TestCase.java:44)

at cucumber.runner.Runner.runPickle(Runner.java:40)

at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)

at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)

at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)

at cucumber.api.junit.Cucumber.runChild(Cucumber.java:124)

at cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)

at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:133)

at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)

at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)

at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)

at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)

at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)

at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)

at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)

... 68 more


    Then I expect to receive status code 200 # HelloStepDefs.iExpectToReceiveStatusCode(int)

    And I expect to receive Hello message    # HelloStepDefs.iExpectToReceiveMessage(String)


Failed scenarios:

src/test/resources/features/Hello.feature:4 # Saying hello to the Server


1 Scenarios (1 failed)

4 Steps (1 failed, 2 skipped, 1 passed)

0m2.389s


________________________________

**Comment by Hakky54** [comment]
It looks like an issue with the truststore within the client project. This specific exception could mean:
The truststore is:
- empty,
- not found, or
- couldn't be opened

The valid location for the truststore.jks and identity.jks are:
- mutuals-tls/client/src/test/resources/identity.jks
- mutuals-tls/client/src/test/resources/truststore.jks

Could you check the above options? If it is still not resolved, let's do a remote session so I can assist you instantly through a video call.

**Comment by Hakky54** [comment]
It looks like an issue with the truststore within the client project. This specific exception could mean:
The truststore is:
- empty,
- not found, or
- couldn't be opened

The valid location for the truststore.jks and identity.jks are:
- mutuals-tls/client/src/test/resources/identity.jks
- mutuals-tls/client/src/test/resources/truststore.jks

Could you check the above options? If it is still not resolved, let's do a remote session so I can assist you instantly through a video call.

**Comment by mpkmtv** [comment]
Here they are:


~/GitHub/mtls$ ls -l client/src/test/resources/

total 64

drwxr-xr-x  11 wdavid  staff   352B Apr 19 13:06 ./

drwxr-xr-x   4 wdavid  staff   128B Apr 19 12:52 ../

-rw-r--r--   1 wdavid  staff    86B Apr 19 13:19 application.yml

-rw-r--r--   1 wdavid  staff   1.8K Apr 19 13:03 client-private.key

-rw-r--r--   1 wdavid  staff   1.1K Apr 19 13:01 client-signed.cer

-rw-r--r--   1 wdavid  staff   2.4K Apr 19 13:03 client-signed.p12

-rw-r--r--   1 wdavid  staff   1.0K Apr 19 12:57 client.csr

-rw-r--r--   1 wdavid  staff   2.5K Apr 19 13:03 client.p12

drwxr-xr-x   3 wdavid  staff    96B Apr 19 12:52 features/

-rw-r--r--   1 wdavid  staff   2.4K Apr 19 13:03 identity.jks

-rw-r--r--   1 wdavid  staff   901B Apr 19 13:06 truststore.jks

~

[cid:6f4fdbf9-ee19-4cf2-82ea-fa4970f5baba]

[cid:6142a971-afc7-45ab-8918-2a8a991b1712]
________________________________

**Comment by mpkmtv** [comment]
I cleaned some changes I made and recompiled the code .
Now I'm more confused . I got different exception .
sorry for this ...



14:43:11.239 [main] DEBUG org.springframework.test.context.support.TestPropertySourceUtils - Adding inlined properties to environment: {spring.jmx.enabled=false, server.port=-1}

2019-04-30 14:43:11.702  INFO 98094 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Starting HelloStepDefs on davids-MacBook-Pro-2.local with PID 98094 (started by wdavid in /Users/wdavid/GitHub/mtls/client)

2019-04-30 14:43:11.704  INFO 98094 --- [           main] n.a.client.stepdefs.HelloStepDefs        : No active profile set, falling back to default profiles: default

2019-04-30 14:43:12.806  INFO 98094 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Started HelloStepDefs in 1.564 seconds (JVM running for 2.643)

Feature: Securing the connection between you and the world


  @Demo

  Scenario: Saying hello to the Server       # src/test/resources/features/Hello.feature:4

    Given Server is alive                    # HelloStepDefs.serverIsAlive()

    When I say hello                         # HelloStepDefs.iSayHello()

      javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate

at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)

at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)

at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1779)

at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)

at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1156)

at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1266)

at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1178)

at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)

at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)

at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)

at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)

at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)

at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)

at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

at nl.altindag.client.stepdefs.HelloStepDefs.iSayHello(HelloStepDefs.java:28)

at ✽.I say hello(src/test/resources/features/Hello.feature:6)


    Then I expect to receive status code 200 # HelloStepDefs.iExpectToReceiveStatusCode(int)

    And I expect to receive Hello message    # HelloStepDefs.iExpectToReceiveMessage(String)


Failed scenarios:

src/test/resources/features/Hello.feature:4 # Saying hello to the Server


1 Scenarios (1 failed)

4 Steps (1 failed, 2 skipped, 1 passed)

0m2.225s

________________________________

**Comment by Hakky54** [comment]
This exception will be thrown if the certificate is untrusted by one of the sides. So it means that the certificate of the server is not in the truststore of the client or the other way around, so it could be that the certificate of the client is not in the truststore of the server. Could you reimport the certificate of the client into the truststore of the server and also reimport the certificate of the server into the truststore of the client and recompile and start the test again?

**Comment by mpkmtv** [comment]
Wait,

I have THE SAME  ca-root certificate in the server and the client  truststores:

[cid:e94f3828-cb29-4cac-820f-5294641613e3]




________________________________

**Comment by mpkmtv** [comment]
Could this be a problem?


~/GitHub/mtls$  keytool -importkeystore -srckeystore client/src/test/resources/identity.jks -destkeystore client/src/test/resources/client.p12 -srcstoretype jks -deststoretype pkcs12 -srcstorepass secret -deststorepass secret

Importing keystore client/src/test/resources/identity.jks to client/src/test/resources/client.p12...

Import command completed:  0 entries successfully imported, 0 entries failed or cancelled

________________________________

**Comment by Hakky54** [comment]
Yes, that part doesn't look ok. It should have give you the following message: `Import command completed:  1 entries successfully imported, 0 entries failed or cancelled`

Could you please try again exactly all the steps from chapter `Creating a Certificate Authority`
Somehow exporting your identity certificate and signing it with the root-ca has not happend.

**Comment by mpkmtv** [comment]
I did everything from scratch and still getting the exception. Can we do a session with shared desktop?
It might be very helpful



16:21:17.931 [main] DEBUG org.springframework.test.context.support.TestPropertySourceUtils - Adding inlined properties to environment: {spring.jmx.enabled=false, server.port=-1}

2019-04-30 16:21:18.399  INFO 366 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Starting HelloStepDefs on davids-MacBook-Pro-2.local with PID 366 (started by wdavid in /Users/wdavid/GitHub/mtls/client)

2019-04-30 16:21:18.400  INFO 366 --- [           main] n.a.client.stepdefs.HelloStepDefs        : No active profile set, falling back to default profiles: default

2019-04-30 16:21:19.463  INFO 366 --- [           main] n.a.client.stepdefs.HelloStepDefs        : Started HelloStepDefs in 1.529 seconds (JVM running for 2.606)

Feature: Securing the connection between you and the world


  @Demo

  Scenario: Saying hello to the Server       # src/test/resources/features/Hello.feature:4

    Given Server is alive                    # HelloStepDefs.serverIsAlive()

    When I say hello                         # HelloStepDefs.iSayHello()

      javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate

at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)

at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)

at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1779)

at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)

at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1156)

at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1266)

at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1178)

at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)

at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)

at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)

at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)

at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)

at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)

at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)

at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)

at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)

at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

at nl.altindag.client.stepdefs.HelloStepDefs.iSayHello(HelloStepDefs.java:28)

at ✽.I say hello(src/test/resources/features/Hello.feature:6)


    Then I expect to receive status code 200 # HelloStepDefs.iExpectToReceiveStatusCode(int)

    And I expect to receive Hello message    # HelloStepDefs.iExpectToReceiveMessage(String)


Failed scenarios:

src/test/resources/features/Hello.feature:4 # Saying hello to the Server


1 Scenarios (1 failed)

4 Steps (1

________________________________

**Comment by Hakky54** [comment]
Sure, add me at discord and let's continue over there. My username is Hakky54#8471

**Comment by mpkmtv** [comment]
Thanks,

I created discord account , but i'm new to it. Here is the chat invitation : https://discord.gg/5DqB4E

David
________________________________

**Comment by Hakky54** [comment]
David and I did a remote video session and retried the steps described in the Readme and it worked with the first try. Looking at the exception what David had previously it could mean that the certificate was not trusted because it wasn't signed properly or wasn't trusted.

**Comment by sameer-dighe** [comment]
Hey @Hakky54 , did you solve above issue wuth @mpkmtv ? I am also getting same issue and struggling with same.

**Comment by Hakky54** [comment]
Yes we resolved the issue. We could not find the root cause but we started from scratch with the tutorial and followed everything step by step. So my assumption was that he missed a step in the tutorial back then. Can you try to run the script test-all-scenarios.sh file and share your results here?

**Comment by sameer-dighe** [comment]
I checked your repo but you mentioned that Java 11 is must and I am on jdk 8 and I can't upgrade it.

**Comment by sameer-dighe** [comment]
do you have some time to for video call?

**Comment by sameer-dighe** [comment]
> Yes we resolved the issue. We could not find the root cause but we started from scratch with the tutorial and followed everything step by step. So my assumption was that he missed a step in the tutorial back then. Can you try to run the script test-all-scenarios.sh file and share your results here?

do you have some time for video call?

**Comment by Hakky54** [comment]
I am not available today and tomorrow, but from Sunday onwards I am available everyday. Let's continue the chat on Gitter and discuss the next steps https://gitter.im/hakky54/mutual-tls-ssl

**Comment by sameer-dighe** [comment]
so finally I & @Hakky54 resolved the issue and it was something to do with classpath and truststore wasn't getting initialised properly. it got resolved after using the absolute path for store. more to it there were some other small problems but those got resolved in less time that the first one.

**Comment by chetnajoshi889** [comment]
Hi @sameer-dighe , I'm also getting same error like Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

Could you please help me to resolve this error?

**Comment by Hakky54** [comment]
> * The truststore is empty
> * The password of the truststore is empty
> * The truststore is not found, or
> * The truststore couldn't be opened (due to access permissions for example).

Hi @chetnajoshi889 your issue might be related to one of the options quoted above. Or your truststore does not contain the trusted certificates

**Comment by rajatzeal** [comment]
Hi @Hakky54 ,
I am also facing the same issue, tried all sorts of corrections but no luck.
Please assist me in solving this, have an urgent delivery to make and I am stuck on this point since past two days.

**Comment by Hakky54** [comment]
Hi @rajatzeal 
Can you maybe share some code snippets, than I will be able to understand how you setup your client with ssl.

**Comment by rajatzeal** [comment]
![3F718C57-91AC-463A-958D-076FB2256262](https://user-images.githubusercontent.com/102432032/201875605-896e0b09-67cd-42a1-9dba-21357a6eeb24.jpeg)

this is the basic setup for initialising Google chrome and it’s settings

**Comment by rajatzeal** [comment]
I can share my screen if you are available for a call, I’m really stuck with the issue and would appreciate your help

**Comment by Hakky54** [comment]
I can understand your setup is not working. The ssl configuration of Selenium with the ChromeDriver is just not working with only the ChromeOptions. I would suggest to have a look at this stackoverflow answer here: https://stackoverflow.com/a/56170148/6777695

In the example above all https requests are getting intercepted and being executed alongside with ayour custom sslcontext.

The author has made his code snippet available here at GitHub: https://github.com/patricsteiner/seleniumSslProxy
I am fully booked today unfortunatelly and tomorrow, so I don't have time... But looking at the code snippet on that GitHub page I think you will get it working. Please give it a try and I still can try to assist you if you share your progress over here.

**Comment by rajatzeal** [comment]
Ok , will try to check with these solutions.
Meanwhile please try if you could take out time today, just a quick call would do

**Comment by Hakky54** [comment]
I will be available at 13:00 CEST till 14:00 CEST, so we can have a look at it. Let's use Teamviewer. You can share your teamviewer id and password on the private Gitter chat with me directly

**Comment by Hakky54** [comment]
We did a short call with @rajatzeal and it seems like his HttpClient was not trusting the certificate of the server. It is the same point which I mentioned here: https://github.com/Hakky54/mutual-tls-ssl/issues/1#issuecomment-485066443

He needs to export the server certificate, create a SSLContext and configure his HttpClient so the client will trust the server.

**Comment by Hakky54** [comment]
I found the anser of ChatGPT useful, so I am sharing it here. Hopefully it will be useful for others who end up at this page while having the same exception:

> This error message is indicating that an SSL/TLS connection is failing due to a problem with the trust anchors (i.e., trusted certificate authorities) used by the client to verify the server's certificate.
>
> The message "the trustAnchors parameter must be non-empty" means that the client is unable to find any trusted certificate authorities in its trust store, which is causing the SSL/TLS handshake to fail.
>
> Here are some steps you can take to resolve this issue:
>
> Ensure that the correct trust store is being used: Make sure that the client is using the correct trust store for the SSL/TLS connection. For example, the default trust store for the JVM can be found at $JAVA_HOME/jre/lib/security/cacerts, but some applications may use a custom trust store.
>
> Verify the trust store contains the necessary certificates: Ensure that the trust store contains the necessary root and intermediate certificates for the SSL/TLS connection. You can use the keytool utility to list the contents of the trust store and verify that the correct certificates are present.
>
> Import the necessary certificates: If the necessary certificates are missing from the trust store, you can import them using the keytool utility. You will need to obtain the necessary certificates from the certificate authority that issued the server's certificate.
>
> Check the server certificate: Make sure that the server's certificate is valid and not expired. Also, verify that the certificate was issued by a trusted certificate authority and that the certificate chain is complete (i.e., the root and intermediate certificates are installed on the server).
>
> By following these steps, you should be able to resolve the issue with the trust anchors and establish a successful SSL/TLS connection.

**Comment by Hakky54** [comment]
### I noticed that a-lot of developers are facing this exception or similar ones. If anyone has trouble resolving these kind of issues feel free to ping me, I am able to provide support. My mail address is hakan.altindag@thunderberry.nl
